### PR TITLE
fix: use versioned extra-data

### PR DESCRIPTION
**Pull request by nuzar**
Fix https://github.com/flathub/com.jianguoyun.Nutstore/issues/20

### CODE REVIEW

**Comment by nuzar** [comment]
flatpak-external-data-checker test pass

```bash
> flatpak run org.flathub.flatpak-external-data-checker com.jianguoyun.Nutstore.yaml
INFO    src.manifest: Loading module from shared-modules/libsoup/libsoup-2.4.json
INFO    src.manifest: Checking 4 external data items
INFO    src.manifest: Skipped check [1/4] archive unifdef/unifdef-2.12.tar.xz (from com.jianguoyun.Nutstore.yaml)
INFO    src.manifest: Skipped check [2/4] archive webkitgtk-4.0/webkitgtk-2.44.0.tar.xz (from com.jianguoyun.Nutstore.yaml)
INFO    src.manifest: Started check [3/4] extra-data nutstore/nutstore_linux_dist_x64.tar.gz (from com.jianguoyun.Nutstore.yaml)
INFO    src.manifest: Skipped check [4/4] archive libsoup-2.4/libsoup-2.74.3.tar.xz (from shared-modules/libsoup/libsoup-2.4.json)
INFO    src.manifest: Finished check [4/4] extra-data nutstore/nutstore_linux_dist_x64.tar.gz (from com.jianguoyun.Nutstore.yaml)
INFO    src.main: Check finished with 0 error(s)
```

**Comment by nuzar** [comment]
flatpak-external-data-checker expected failure test pass
```bash
> flatpak run org.flathub.flatpak-external-data-checker com.jianguoyun.Nutstore.yaml
INFO    src.manifest: Loading module from shared-modules/libsoup/libsoup-2.4.json
INFO    src.manifest: Checking 4 external data items
INFO    src.manifest: Skipped check [1/4] archive unifdef/unifdef-2.12.tar.xz (from com.jianguoyun.Nutstore.yaml)
INFO    src.manifest: Skipped check [2/4] archive webkitgtk-4.0/webkitgtk-2.44.0.tar.xz (from com.jianguoyun.Nutstore.yaml)
INFO    src.manifest: Started check [3/4] extra-data nutstore/nutstore_linux_dist_x64.tar.gz (from com.jianguoyun.Nutstore.yaml)
INFO    src.manifest: Skipped check [4/4] archive libsoup-2.4/libsoup-2.74.3.tar.xz (from shared-modules/libsoup/libsoup-2.4.json)
WARNING src.lib.externaldata: Source nutstore_linux_dist_x64.tar.gz: remote data changed
INFO    src.manifest: Finished check [4/4] extra-data nutstore/nutstore_linux_dist_x64.tar.gz (from com.jianguoyun.Nutstore.yaml)
BROKEN|LATEST: nutstore_linux_dist_x64.tar.gz
 Has a new version:
  URL:       https://dc-pkg-cdn.jianguoyun.com/static/exe/st/6.3.0/nutstore_client-6.3.0-linux-x86_64-public.tar.gz
  MD5:       fe11cf29877e7b8b064281c93fb8948a
  SHA1:      2e79540ad2fc7e60369d8aca05cbbab88bd922a1
  SHA256:    38a2a6a80577c12c5168615f23cfe5a9ed3442e4dd18e8fe6651bf806bc1d758
  SHA512:    352cbab37af0384fdbb617d584d80982a467298bd6f816989a121add27518bc789227e8164d047d007a4cb1ae3c98dc4e4b0d8d584c2f94789efff9b20d8e794
  Size:      62321049
  Version:   6.3.0
  Timestamp: 2024-05-23 01:33:38

INFO    src.main: Check finished with 0 error(s)
```

**Comment by nuzar** [comment]
@barthalion Hi, can you take a look at this. Since this package is not installable now, and @chenyuanrun seem to be inactive for months.
I have used the new version for 3 weeks.
image

**Comment by nuzar** [comment]
Oh, I forgot to add release 6.3.0 in com.jianguoyun.Nutstore.metainfo.xml.

**Comment by nuzar** [comment]
> Oh, I forgot to add release 6.3.0 in com.jianguoyun.Nutstore.metainfo.xml.

@chenyuanrun Hi, 你能合并下 https://github.com/flathub/com.jianguoyun.Nutstore/pull/35 吗？这个 PR 更新到了 6.3.2 并且正确添加了 release。

**Comment by chenyuanrun** [comment]
@nuzar 已合入

**Pull request merged**
